version: "3"
services:

  proxy:
    build: ./nginx
    image: proxy
    ports:
      - "80:80"
    
  blog:
    build: ./ghost
    environment:
      NODE_ENV: development
    image: blog
    ports:
      - "2368:2368"